# @package _global_
defaults:
  - /model/base@model
  - _self_

agent:
  name: qa_wiki
  instructions: You are a Web Information Seeking Master.

toolkits:
  wiki:
    name: wiki
    mode: customized
    customized_filepath: examples/rl_train/wiki_tool.py
    customized_classname: WikiToolkit
    activated_tools: null
